### ISSUE TITLE
Yellow color of current note is kinda hard to see against the grey background.

### ISSUE THREAD

**Issue by eriksvedang** [hisekaldma/Polyhymnia#1]

**Comment by eriksvedang** [comment]
I think the underlining and bold text could be enough, no need to change color perhaps..?

**Comment by hisekaldma** [comment]
I tried a couple of different colors, and nothing feels as good as the bright yellow, even if it’s easier to read. It loses the feeling that they light up like a step sequencer. So yeah, the underline and slightly increased contrast will probably have to do.

**Comment by eriksvedang** [comment]
OK, maybe a slighter darker background could help instead... sorry for this nitpick but I keep thinking about it when using the web app (and I obsess over these things in the color schemes I use when coding). I guess the problem is that it feels like they "disappear" rather than light up. I think it might be worth revisiting at some point at least.

**Comment by hisekaldma** [comment]
Nitpick is good. The native app will have a dark background and allow changing syntax colors. So for real use, I don't think it will be a problem.

**Comment by eriksvedang** [comment]
Sounds good!
